#!/bin/sh

system_type=$(uname -s)

# Install Homebrew and bundle
install_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  BREW_PREFIX=$(brew --prefix)

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # Symlink to installed coreutils
  ln -s "${BREW_PREFIX}/bin/gsha256sum" "${BREW_PREFIX}/bin/sha256sum"

  # Switch to using brew-installed bash as default shell
  if ! fgrep -q "${BREW_PREFIX}/bin/bash" /etc/shells; then
    echo "${BREW_PREFIX}/bin/bash" | sudo tee -a /etc/shells;
    chsh -s "${BREW_PREFIX}/bin/bash";
  fi

  # Doctor
  brew doctor

  # Remove outdated versions from the cellar
  brew cleanup
}

# Configure macOS
configure_macos() {
  if [ -d "$HOME/.macos" ]; then
    echo "Configuring macOS"
    # $HOME/.macos
  fi
}

# Configure iTerm
configure_iterm() {
  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi
}

if [ "$system_type" = "Darwin" ]; then
  install_brew
  configure_macos
  configure_iterm
fi
