#!/bin/sh

system_type=$(uname -s)
cpu_type=$(uname -m)


###############################################################################
# Bootstrap system                                                            #
###############################################################################
if [ "$system_type" = "Darwin" ]; then
  install_brew
  configure_macos
  configure_iterm
  configure_zsh
  load_fonts
fi

# -------------------------------
# Install Homebrew and Brewfile bundle (formulae and casks)
# -------------------------------
install_brew() {
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  # Link Homebrew casks in `/Applications` rather than `~/Applications`
  if [[ -f "`which brew`" ]]; then
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  fi
  
  BREW_PREFIX=$(brew --prefix)

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global

    # Workaround to install dockutil
    brew install jq
    DLURL=$(curl --silent "https://api.github.com/repos/kcrawford/dockutil/releases/latest" | jq -r .assets[].browser_download_url | grep pkg)
    curl -sL ${DLURL} -o /tmp/dockutil.pkg
    sudo installer -pkg "/tmp/dockutil.pkg" -target /
    rm /tmp/dockutil.pkg
  fi

  brew doctor
  brew update
  brew upgrade
  brew cleanup
}

# -------------------------------
# Configure zsh
# -------------------------------
configure_zsh() {
  # Set default shell as brew-installed zsh
  if ! fgrep -q "${BREW_PREFIX}/bin/zsh" /etc/shells; then
    echo "${BREW_PREFIX}/bin/zsh" | sudo tee -a /etc/shells;
    chsh -s "${BREW_PREFIX}/bin/zsh";
  fi

  # Install oh-my-zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

# -------------------------------
# Configure macOS
# -------------------------------
configure_macos() {
  if [ -a "$HOME/.macos" ]; then
    echo "Configuring macOS"
    $HOME/.macos
  fi
}

# -------------------------------
# Configure iTerm
# -------------------------------
configure_iterm() {
  if [ -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi
}

# -------------------------------
# Load fonts
# -------------------------------
load_fonts() {
  if [ -d "$HOME/.fonts" ]; then
    echo "Loading fonts into the current user"
    fd . ~/.fonts -e ttf | xargs -I _ cp _ "$HOME/Library/Fonts"
  fi
}
