#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Get YouTube Transcript
# @raycast.mode fullOutput

# Optional parameters:
# @raycast.icon 🧠
# @raycast.argument1 { "type": "text", "placeholder": "Video URL", "optional": false, "percentEncoded": true}
# @raycast.argument2 { "type": "text", "placeholder": "File name", "optional": true}

# Documentation:
# @raycast.description Run fabric -y on the input text of a YouTube video to get the transcript from.
# @raycast.author Daniel Miessler
# @raycast.authorURL https://github.com/danielmiessler


# Set PATH to include common locations and $HOME/go/bin
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/go/bin:$PATH"

# Use the PATH to find and execute fabric
COMMAND=$(command -v fabric || command -v fabric-ai) || (echo "Error: Neither 'fabric' nor 'fabric-ai' is installed." && exit 1)
$COMMAND -y "${1}" "${2}"
